version: "3"
services:

 car_db:
  image: postgres:latest
  restart: unless-stopped
  container_name: car_vote_db
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  env_file:
   - .env

 car_api:
  build: ./code
  container_name: car_vote_api
  restart: unless-stopped
  ports:
   - "${DJANGO_PORT}:8080"
  env_file:
   - .env
  volumes:
   - ./code:/code
  depends_on:
   - car_db
  links:
   - car_db:car_db
  entrypoint: "bash /code/docker-entrypoint.sh"
  command: "runserver 0.0.0.0:8080"

